"""Size scenario S1 against SPEC §8.1 and check the D1 invariant across a sweep.

Reads real July 22 2026 hourly facts (EIA-930) for the claim windows, then does the
ledger arithmetic from SPEC §6.3 with the §17 defaults. Writes scenarios/S1_sizing.md.
Run: .venv/Scripts/python.exe prep/size_s1.py
"""
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
WIDE = ROOT / "data" / "raw" / "2026-07-21_24_eia930_hourly_wide.parquet"
OUT = ROOT / "scenarios" / "S1_sizing.md"

# ---- SPEC §17 defaults (assumptions, not facts)
N_DEVICES = 400
MIX = {39.2: 0.7, 78.4: 0.3}                  # kWh per unit : share
KW_PER_39_2 = 11.5                            # kW per 39.2 kWh unit [A]
FLOOR = 0.20
EPS_FRAC = 0.01
AUX_KW = 0.050
WINDOW_H = 6.5                                # 15:00-21:30, the scenario horizon
# §6.3's drain term is drain_hi(now -> t), evaluated at the time the kWh term BINDS, not over the
# whole window. All three S1 claims bind at 21:00 (the end of the AS window, where the CAPACITY
# reservation drops out of slack) - confirmed by the 2026-09-16 practice build, which does the full
# 5-minute bucket sweep. Charging the drain over 6.5 h instead of 6.0 h overstates it by
# 400 x 0.050 kW x 0.5 h = 10 kWh, which exceeds D1's +/-1 kWh pass bar. See PRACTICE-NOTES.md
# FINDING-9.
DRAIN_TO_H = 6.0                              # 15:00 -> 21:00
REGIONS = 5
FEEDER_CAP = 0.80
OUTAGE_H = 0.5
AS_KW, AS_DEPLOY_H = 1500.0, 1.0              # ADER_AS capacity hold, 19:00-21:00
ENERGY_KW, ENERGY_H = 2000.0, 1.0             # ADER_ENERGY, 20:00-21:00
COOP_KW = 3000.0                              # COOP_PEAK power

AVG_KWH = sum(k * s for k, s in MIX.items())
AVG_KW = sum(KW_PER_39_2 * (k / 39.2) * s for k, s in MIX.items())


def size(soc0: float, coop_h: float, with_coop: bool = True) -> dict:
    nameplate = N_DEVICES * AVG_KWH
    kw_total = N_DEVICES * AVG_KW * FEEDER_CAP
    region_kw = (N_DEVICES / REGIONS) * AVG_KW * FEEDER_CAP
    kw_room = kw_total - region_kw                                   # N-1 kW reserve
    e0 = (nameplate * (soc0 - FLOOR) - EPS_FRAC * nameplate
          - AUX_KW * N_DEVICES * DRAIN_TO_H - region_kw * OUTAGE_H)  # §6.2 + §6.3 slack base
    # priority 2: ADER_AS capacity hold
    as_kw = min(AS_KW, kw_room, max(0.0, e0) / AS_DEPLOY_H)
    slack = e0 - as_kw * AS_DEPLOY_H
    # priority 3: COOP_PEAK energy
    coop_kw = min(COOP_KW, kw_room, max(0.0, slack) / coop_h) if with_coop else 0.0
    slack -= coop_kw * coop_h
    # priority 4: ADER_ENERGY (overlaps the AS hold in kW)
    kw_term, kwh_term = kw_room - as_kw, max(0.0, slack) / ENERGY_H
    energy_kw = min(ENERGY_KW, kw_term, kwh_term)
    binding = "none" if energy_kw >= ENERGY_KW else ("kwh_slack" if kwh_term <= kw_term else "kw_room")
    return dict(e0=e0, kw_room=kw_room, as_kw=as_kw, coop_kw=coop_kw, energy_kw=energy_kw,
                binding=binding, slack_after=slack - energy_kw * ENERGY_H)


def d1(soc0: float, coop_h: float) -> dict:
    w, wo = size(soc0, coop_h, True), size(soc0, coop_h, False)
    cut = (wo["energy_kw"] - w["energy_kw"]) * ENERGY_H
    slack_without = wo["e0"] - wo["as_kw"] * AS_DEPLOY_H - ENERGY_KW * ENERGY_H
    expected = min(max(w["coop_kw"] * coop_h - slack_without, 0.0), ENERGY_KW * ENERGY_H)
    truth_20 = N_DEVICES * AVG_KWH * (soc0 - FLOOR) - w["coop_kw"] * coop_h - AUX_KW * N_DEVICES * 5.0
    reasonable_as_ok = truth_20 - ENERGY_KW * ENERGY_H >= AS_KW * AS_DEPLOY_H   # reasonable admits energy in full
    return dict(w=w, wo=wo, cut=cut, expected=expected, d1_ok=abs(cut - expected) < 1.0,
                reasonable_as_ok=reasonable_as_ok)


def day_facts() -> str:
    h = pd.read_parquet(WIDE).loc["2026-07-22 01:00":"2026-07-23 00:00"]
    rows = []
    for label, col in [("demand", "demand"), ("net load (D - solar - wind)", "net_load"), ("battery (BAT)", "BAT")]:
        rows.append(f"| peak {label} | {int(h[col].max()):,} MW | hour ending {h[col].idxmax():%H:%M} CT |")
    at = lambda he: h.loc[f"2026-07-22 {he}"]
    rows.append(f"| battery at load-peak hour (HE 18:00) | {int(at('18:00')['BAT']):,} MW | negative = net charging |")
    rows.append(f"| battery at net-load-peak hour (HE 21:00) | {int(at('21:00')['BAT']):,} MW | |")
    return "\n".join(rows)


def main() -> None:
    base = d1(0.80, 3.0)
    lines = [
        "# S1 sizing (generated by prep/size_s1.py; do not hand-edit)",
        "",
        "## Real day: ERCOT 2026-07-22 (EIA-930 hourly, hour ending CT)",
        "| fact | value | note |", "|---|---|---|", day_facts(),
        "",
        "Claim windows follow the data: COOP_PEAK covers the load peak (HE16-HE18); ADER_ENERGY 20:00-21:00 is HE21, the net-load and battery peak.",
        "",
        "## Base case (SPEC §8.1 defaults: start SoC 80%, co-op shave 3 h)",
        f"- E0 after eps, aux, N-1 kWh: **{base['w']['e0']:,.0f} kWh**; kW room after N-1: **{base['w']['kw_room']:,.0f} kW**",
        f"- ADER_AS {base['w']['as_kw']:,.0f} kW · COOP_PEAK {base['w']['coop_kw']:,.0f} kW · ADER_ENERGY **{base['w']['energy_kw']:,.0f} kW** (binding: `{base['w']['binding']}`)",
        f"- Without co-op: ADER_ENERGY {base['wo']['energy_kw']:,.0f} kW",
        f"- D1: cut {base['cut']:,.0f} kWh vs expected {base['expected']:,.0f} kWh → **{'PASS' if base['d1_ok'] else 'FAIL'}**",
        f"- reasonable keeps AS deliverable after 20:00: **{base['reasonable_as_ok']}** (False = the silent miss S1 needs)",
        "",
        "## Sweep: where D1 binds (ADER_ENERGY admitted kW / cut kWh / binding / reasonable AS ok)",
        "| start SoC \\ shave h | " + " | ".join(f"{h:g} h" for h in (1, 2, 3, 4)) + " |",
        "|---|" + "---|" * 4,
    ]
    for soc in (0.5, 0.6, 0.7, 0.8, 0.9, 1.0):
        cells = []
        for hrs in (1.0, 2.0, 3.0, 4.0):
            r = d1(soc, hrs)
            cells.append(f"{r['w']['energy_kw']:,.0f} / {r['cut']:,.0f} / {r['w']['binding']} / {'ok' if r['reasonable_as_ok'] else 'MISS'}"
                         + ("" if r["d1_ok"] else " D1✗"))
        lines.append(f"| {soc:.0%} | " + " | ".join(cells) + " |")
    lines += ["", "Demo target (SPEC §15): binding `kwh_slack`, cut 800-1,300 kWh, and reasonable = MISS.",
              "Assumptions are SPEC §17 defaults. Do not retune at the event."]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
