"""D1 - the demo invariant. SPEC §8.1, written as arithmetic because the prose reading is ambiguous.

It was written to FAIL before the ledger existed: a D1 that passes with no ledger is testing
nothing. It went green when `control/ledger.py` landed and stays green.

It is the single most load-bearing test in the build: it is what makes slide 2 a demonstration
rather than a narration.

Since 2026-09-24 it is a statement about STAGE 1 only. It drives `Ledger.admit` claim by claim,
which is SPEC 6.3's energy arithmetic, and that still sells ADER_ENERGY 928 kW with a 1,072 kWh
cut. The final decision is lower - 763 kW, binding `reserve` - because the per-device N-1 stage
(SPEC 6.3b) finds that the co-op leaves too little kW with energy behind it to survive losing a
region. Both numbers are true; `tests/unit/test_deliverability.py` pins the second.
"""
from __future__ import annotations

import pytest

# The ledger does not exist yet. _load() is how this test fails at H2 - deliberately, with a
# message that says what is missing rather than a bare ImportError at collection time.
def _load():
    try:
        from control.ledger import Ledger          # noqa: F401
        from scenarios.s1 import build_s1          # noqa: F401
    except ImportError as exc:                     # H2: expected
        pytest.fail(
            f"D1 cannot run yet: {exc}. It needs control/ledger.py and scenarios/s1.py."
        )
    from control.ledger import Ledger
    from scenarios.s1 import build_s1
    return Ledger, build_s1


# ---------------------------------------------------------------- expected values
# From scenarios/S1_sizing.md, generated by prep/size_s1.py at 400 devices, and independently
# reproduced by the 2026-09-16 practice build at 1:8 scale (116.0 kW / 134.0 kWh x 8).
# These are NOT free parameters. If the ledger disagrees, the ledger is wrong until proven
# otherwise - and if the SIZING is wrong, prep/size_s1.py is fixed and this file is regenerated
# from it, never edited to match a run.
EXPECT_ADMITTED_KW = 928.0
EXPECT_TOLERANCE_KW = 10.0
EXPECT_CUT_KWH = 1072.0
D1_TOLERANCE_KWH = 1.0


def _clip(x: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, x))


def test_d1_cut_equals_coop_kwh_minus_slack_without():
    """cut == clip(coop_kwh - slack_without, 0, requested_kwh), within 1 kWh.

    slack_without is the slack in the co-op-REMOVED world AFTER ADER_ENERGY is itself
    subtracted (SPEC §8.1: 9.93 - 2.0 = 7.93). Reading it as "before" double-counts and this
    test fails with a plausible-looking wrong number - which is exactly how it slipped past a
    first typing on 2026-09-16 (PRACTICE-NOTES.md FINDING-4).
    """
    Ledger, build_s1 = _load()

    with_coop = build_s1(include_coop=True)
    led_a = Ledger(with_coop.belief, now=with_coop.t0)
    for claim in sorted(with_coop.claims, key=lambda c: c.priority):
        led_a.admit(claim)

    ader = led_a.admitted_by_id("ADER_ENERGY")
    coop = led_a.admitted_by_id("COOP_PEAK")
    cut_kwh = (ader.requested_kw - ader.admitted_kw) * ader.duration_h
    coop_kwh = coop.admitted_kw * coop.duration_h

    no_coop = build_s1(include_coop=False)
    led_b = Ledger(no_coop.belief, now=no_coop.t0)
    for claim in sorted(no_coop.claims, key=lambda c: c.priority):
        led_b.admit(claim)
    ader_b = led_b.admitted_by_id("ADER_ENERGY")
    slack_without = min(led_b.slack(t, ader_b) for t in led_b.evalgrid(ader_b))

    expected = _clip(coop_kwh - slack_without, 0.0, ader.requested_kwh)
    # The invariant AND the magnitude. Asserting only the invariant would pass for a ledger that
    # admits nothing at all (cut == requested == expected), which is why EXPECT_CUT_KWH exists -
    # it was defined and never used until this was caught on 2026-09-16.
    assert cut_kwh == pytest.approx(EXPECT_CUT_KWH, abs=25.0), (
        f"cut {cut_kwh:,.1f} kWh is not near scenarios/S1_sizing.md's {EXPECT_CUT_KWH:,.0f}. "
        f"D1's formula can hold trivially when the ledger admits ~nothing."
    )
    assert abs(cut_kwh - expected) <= D1_TOLERANCE_KWH, (
        f"D1: cut {cut_kwh:,.1f} kWh != expected {expected:,.1f} kWh "
        f"(coop {coop_kwh:,.1f} - slack_without {slack_without:,.1f}). "
        f"If expected is ~{ader.requested_kwh:,.0f}, you subtracted ADER_ENERGY twice."
    )


def test_d1_binding_reason_is_kwh_slack():
    """Not kw_room, not feeder, not reserve. S1 is sized so the kWh is what binds."""
    Ledger, build_s1 = _load()
    s1 = build_s1(include_coop=True)
    led = Ledger(s1.belief, now=s1.t0)
    for claim in sorted(s1.claims, key=lambda c: c.priority):
        led.admit(claim)
    ader = led.admitted_by_id("ADER_ENERGY")
    assert ader.reason.value == "kwh_slack", (
        f"binding reason is {ader.reason.value!r}. If it is 'feeder' or 'kw_room', S1's scarcity "
        f"is coming from the wrong constraint and the pitch's claim is not what is on screen."
    )


def test_d1_admitted_matches_the_sizing_file():
    """The ledger and prep/size_s1.py are independent implementations of the same arithmetic.

    Them agreeing is a control. They disagreed by 10 kWh until FINDING-9 was fixed on 2026-09-16.
    """
    Ledger, build_s1 = _load()
    s1 = build_s1(include_coop=True)
    led = Ledger(s1.belief, now=s1.t0)
    for claim in sorted(s1.claims, key=lambda c: c.priority):
        led.admit(claim)
    ader = led.admitted_by_id("ADER_ENERGY")
    assert abs(ader.admitted_kw - EXPECT_ADMITTED_KW) <= EXPECT_TOLERANCE_KW, (
        f"ledger admits {ader.admitted_kw:,.1f} kW, scenarios/S1_sizing.md says "
        f"{EXPECT_ADMITTED_KW:,.0f} kW. One of them is wrong. Do not edit this number to match "
        f"the run - find out which."
    )
